# Conclusion

During this project, we noticed many interesting trends in the American housing market. We learned that housing prices vary depending on region as well as location in an urban or rural area. Urban regions in the Northeast tend to have the highest home prices while rural regions in the Midwest tend to have the lowest home prices. One would expect that the pandemic would cause a decrease in the supply and the demand for housing, as well as a decrease in price as many Americans who lost jobs might not be able to afford housing. However, we noticed that the number of houses sold in all regions increased, as well as median home price, and these increases even continued into 2021. These patterns are counter-intuitive and ran contrary to our initial expectations. 

The only limitations that we would like to be able to address would be obtaining the missing data not originally published. During any following investigations, we would like to further investigate the acceleration in the American housing market caused by the pandemic, perhaps including economic data or data on COVID-19 and other health trends, or even more variables in the Redfin data. Overall, we found this topic extremely engaging and would warmly welcome the opportunity to conduct follow-up work.
